## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
notifications:
  email: false
julia:
  - 1.0
  - 1.5
  - nightly
os:
  - linux
  - osx
  - windows
arch:
  - x64
branches:
  only: master
cache:
  directories:
    - ~/.julia/artifacts
jobs:
  fast_finish: true
  allow_failures:
    - julia: nightly
after_success:
  # push coverage results to Coveralls
  - julia -e 'cd(Pkg.dir("SphericalHarmonicExpansions")); using Pkg; Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  - julia -e 'cd(Pkg.dir("SphericalHarmonicExpansions")); using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
