name = "SphericalHarmonics"
uuid = "d05e97ba-4975-5b84-b395-f1b7f6ab0710"
authors = ["Martin Hofmann <m.hofmann@uke.de>"]
version = "0.0.0"

[deps]
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MultivariatePolynomials = "102ac46a-7ee4-5c85-9060-abc95bfdeaa3"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
TypedPolynomials = "afbbf031-7a57-5f58-a1b9-b774a0fad08d"

[compat]
HDF5 = ">= 0.12"
MultivariatePolynomials = ">= 0.3"
TypedPolynomials = ">= 0.2.3"
julia = ">= 1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
