name = "SphericalHarmonicExpansions"
uuid = "504afa71-bae7-47b4-8ec9-3851161806ac"
authors = ["Martin Hofmann <m.hofmann@uke.de>"]
version = "0.1.0"

[deps]
GeneralizedGenerated = "6b9d7cbe-bcb9-11e9-073f-15a7a543e2eb"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MultivariatePolynomials = "102ac46a-7ee4-5c85-9060-abc95bfdeaa3"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
TypedPolynomials = "afbbf031-7a57-5f58-a1b9-b774a0fad08d"

[compat]
GeneralizedGenerated = "0.2.8"
HDF5 = "0.12,0.13, 0.14, 0.15"
MultivariatePolynomials = "0.3"
Reexport = "0.2, 1.0"
TypedPolynomials = "0.2"
julia = "1.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
